### ISSUE TITLE
CORS 문제(생성된 이미지를 firebase에 저장하기 위한 요청 중에 발생)

### ISSUE THREAD

**Issue by JHeeKimm** [what-is-your-ideal-type/FE_what-is-your-ideal-type#48]
## 어떤 버그인가요?

> CORS 문제

## 어떤 상황에서 발생한 버그인가요?

> openAI api로 생성한 이미지 url을 다운로드(fetch사용)해서 firebase storage에 업로드하는 중에 CORS 에러가 떴습니다. 외부 이미지 url이어서 브라우저에서 직접 요청한 것이 원인인듯 합니다.
여러 방법을 시도해봤지만, 결론은 저희는 서버리스 웹앱을 개발중이기 때문에 Cloud Functions 를 사용해 서버리스 실행환경을 만들어서 cors 문제를 해결하는 방법으로 진행해보려고 합니다.

## 예상 결과

> 개발 환경에서든 배포하고 나서든 url 관련한 cors 문제가 일어나지 않길 기대해봅니다.

## 참고할만한 자료(선택)
https://xiubindev.tistory.com/115

**Comment by joshyeom** [comment]
![image](https://github.com/what-is-your-ideal-type/FE_what-is-your-ideal-type/assets/105287510/00c3378f-053d-46ac-bc1b-2fe26367fd1a)
![image](https://github.com/what-is-your-ideal-type/FE_what-is-your-ideal-type/assets/105287510/cac1ce87-7ca1-4f6b-9e61-3bfdbde06aeb)

**Comment by joshyeom** [comment]
#49 해결
