### ISSUE TITLE
Bug : open api 요청 시 매번 요청에 성공하지 못하는 문제

### ISSUE THREAD

**Issue by sennydayk** [what-is-your-ideal-type/FE_what-is-your-ideal-type#57]
## 어떤 버그인가요?

> ai 생성 api 요청 시, 3번에 한 번 꼴로 403 error, 409 error가 동시에 발생하며 이미지가 생성되지 않는 문제

## 어떤 상황에서 발생한 버그인가요?

> 코드 수정 없이 동일한 환경에서 ai 생성 api 요청을 했을 때 정상적으로 이미지가 출력될 때도 있지만 한 번씩 403, 409 error가 발생하며 이미지가 생성되지 않는 문제가 발생합니다. 

## 예상 결과

> api 요청 시마다 이미지를 정상적으로 불러오는 것

## 참고할만한 자료(선택)

에러 스크린샷 첨부합니다.
![image](https://github.com/what-is-your-ideal-type/FE_what-is-your-ideal-type/assets/141703065/d82a7b2a-11c9-4938-b796-72f043489ceb)

**Comment by joshyeom** [comment]
https://community.openai.com/t/problem-with-public-access-to-dalle-generated-urls/59365
